name: Build and run tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TaskMaster/TaskMaster.sln
    - name: Build
      run: dotnet build TaskMaster/TaskMaster.sln --no-restore
    - name: Test
      run: dotnet test TaskMaster/TaskMaster.UnitTests/TaskMaster.UnitTests.csproj
